version: "3.1" 
services:
  server:
    build:
      context: setupEvn/images/Nginx
    restart: 'no'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./source/public:/var/www/html/public
      - ./app/dist:/var/www/html/app
      - ./setupEvn/images/Nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/var/log/nginx/
    depends_on:
      - api
  api:
    build:
      context: setupEvn/images/Php
    restart: always
    depends_on:
      - db
    volumes:
      - ./source:/var/www/html
      - ./setupEvn/images/Php/Config/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./setupEvn/images/Php/Config/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
    ports:
      - 9002:9000
  db:
    build:
      context: setupEvn/images/Mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./setupEvn/images/Mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=a123456
      - MYSQL_DATABASE=chat_db
      - MYSQL_USER=peterpan
      - MYSQL_PASSWORD=peterpanfly
    ports:
      - 3309:3306

#disk
volumes:
  dir-site:
    driver_opts:
      device: source/
      o: bind
      type: tmpfs