version: "3.1" 
services:
  web:
    image: nginx
    container_name: server-nginx
    restart: always
    hostname: nginx
    networks:
      - my-network
    ports:
      - "8888:80"
      - "443:443"
    volumes:
     - .././source:/home/source
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # environment:
    #  - NGINX_HOST=huydvnginx.com
    #  - NGINX_PORT=80
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  mysql:
    image: "mysql"
    container_name: huydv-mysql
    restart: always
    hostname: mysql
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: a123456
      MYSQL_DATABASE: huydv
      MYSQL_USER: huydv
      MYSQL_PASSWORD: a123456
    volumes:
      - .././db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
  php:
    container_name: huydv-php
    build:
      dockerfile: DockerfilePhp
      context: ./
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - .././source:/home/source

#network
networks:
  my-network:
    driver: bridge

#disk
volumes:
  dir-site:
    driver_opts:
      device: ../source/
      o: bind
      type: tmpfs