version: "3.1" 
services:
  web:
    image: nginx
    container_name: server-nginx
    build:
      dockerfile: Nginx/DockerfileNginx
      context: ./images/
    restart: always
    hostname: nginx
    networks:
      - my-network
    ports:
      - "8888:80"
    volumes:
     - .././source/public:/home/source/public
     - ./images/Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
     - .././nginx/:/var/log/nginx/
  mysql:
    image: "mysql"
    build:
      dockerfile: Mysql/DockerfileMysql
      context: ./images/
    container_name: huydv-mysql
    restart: always
    hostname: mysql
    networks:
      - my-network
    volumes:
      - .././db:/var/lib/mysql
      - ./images/Mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3309:80
#  phpmyadmin:
#    image: "phpmyadmin/phpmyadmin"
#    container_name: phpmyadmin
#    restart: always
#    hostname: phpmyadmin
#    networks:
#      - my-network
#    environment:
#      - PMA_HOST=huydv-mysql
#    ports:
#      - 8081:80
  php:
    container_name: huydv-php
    build:
      dockerfile: Php/DockerfilePhp
      context: ./images/
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - .././source:/home/source
      - ./images/Php/Config/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./images/Php/Config/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
    ports:
      - 8889:80
#network
networks:
  my-network:
    driver: bridge

#disk
volumes:
  dir-site:
    driver_opts:
      device: ../source/
      o: bind
      type: tmpfs