version: "3.1" 
services:
  web:
    image: nginx
    container_name: server-nginx
    restart: always
    hostname: nginx
    networks:
      - my-network
    ports:
      - "8888:80"
      - "443:443"
    volumes:
     - .././source/public/:/home/source/public/
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # environment:
    #  - NGINX_HOST=huydvnginx.com
    #  - NGINX_PORT=80
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  mysql:
    image: "mysql"
    container_name: huydv-mysql
    restart: always
    hostname: mysql
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: a123456
      MYSQL_DATABASE: huydv
      MYSQL_USER: huydv
      MYSQL_PASSWORD: a123456
    volumes:
      - .././db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:80
#  phpmyadmin:
#    image: "phpmyadmin/phpmyadmin"
#    container_name: phpmyadmin
#    restart: always
#    hostname: phpmyadmin
#    networks:
#      - my-network
#    environment:
#      - PMA_HOST=huydv-mysql
#    ports:
#      - 8081:80
  php:
    container_name: huydv-php
    build:
      dockerfile: DockerfilePhp
      context: ./
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - .././source:/home/source
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
#    container_name: elasticsearch
#    environment:
#      - node.name=es01
#      - cluster.name=elasticsearch-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    # volumes:
#    #   - .././source/dataEs01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
#    networks:
#      - my-network
#network
networks:
  my-network:
    driver: bridge

#disk
volumes:
  dir-site:
    driver_opts:
      device: ../source/
      o: bind
      type: tmpfs