version: "3.1" 
services:
  web:
    build:
      context: ./images/Nginx
    restart: 'no'
    ports:
      - 80:80
      - 443:443
    volumes:
      - .././source/public:/var/www/html/public
      - ./images/Nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .././nginx/:/var/log/nginx/
    depends_on:
      - api

  api:
    build:
      dockerfile: Php/DockerfilePhp
      context: ./images/
    restart: always
    depends_on:
      - db
    volumes:
      - .././source:/var/www/html
      - ./images/Php/Config/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./images/Php/Config/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
    ports:
      - 9001:9000

  db:
    build:
      dockerfile: Mysql/DockerfileMysql
      context: ./images/
    restart: always
    volumes:
      - .././db:/var/lib/mysql
      - ./images/Mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306

#disk
volumes:
  dir-site:
    driver_opts:
      device: ../src/
      o: bind
      type: tmpfs